
###   GETTING A LIST OF CLIENT'S ACCOUNTS (ПОЛУЧЕНИЕ СПИСКА СЧЕТОВ КЛИЕНТОВ)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Getting client's accounts with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение счетов клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts

###
// Getting client's accounts with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение счетов клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts

###
// Getting client's accounts with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение счетов клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Invalid UUID string(Bad request) (Некоректный ввод id)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962/accounts

###
// Client not found (Клиент не найден)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120099/accounts


###             GETTING ACCOUNT'S AMOUNT (ПОЛУЧЕНИЕ БАЛАНСА СЧЕТА)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Getting account's amount: 12345678910111213150 client with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение баланса счета: 12345678910111213150  клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
// Getting account's amount: 12345678910111213149 client with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение баланса счета: 12345678910111213149  клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###
// Getting account's amount: 12345678910111213148 client with id = 4f9a97c4-8300-11ee-b962-0242ac120011
// Получение баланса счета: 12345678910111213148  клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###
// Getting account's amount: 12345678910111213147 client with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Получение баланса счета: 12345678910111213147  клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Account not found (Аккаунт не найден)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213148

###
// Incorrect account number (Неверный номер счета)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213121321123123

###
// Incorrect account number (Неверный номер счета))
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/123456789101112131qwe


###          ADDING AN AMOUNT TO AN ACCOUNT (ЗАЧИСЛЕНИЯ СРЕДСТВ НА СЧЕТ)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Adding an amount to an account: 12345678910111213150 client with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Зачисление средств на счет: 12345678910111213150, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213150,
  "amount": 123
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###

// Adding an amount to an account: 12345678910111213149 client with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// Зачисление средств на счет: 12345678910111213149, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213149,
  "amount": 100.50
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

// Adding an amount to an account: 12345678910111213148 client with id = 4f9a97c4-8300-11ee-b962-0242ac120011
// Зачисление средств на счет: 12345678910111213148, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213148,
  "amount": 1000
}

###
// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Adding an amount to an account: 12345678910111213147 client with id = 4f9a97c4-8300-11ee-b962-0242ac120012
// Зачисление средств на счет: 12345678910111213147, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213147,
  "amount": 0.99
}

###
// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Adding an amount to an account: 12345678910111213147 client with id = 4f9a97c4-8300-11ee-b962-0242ac120012
// Зачисление средств на счет: 12345678910111213147, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213147,
  "amount": 10000
}

###
// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Account not found (Аккаунт не найден)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213149,
  "amount": 0.99
}

###
// Incorrect account number (Некоректный номер счета)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 1234567891011121314,
  "amount": 13
}

###
// Incorrect account number (Некоректный номер счета)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 123456789101112131499,
  "amount": 13
}

###
// Incorrect account number (Некоректный номер счета)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": "1234567891011121314q4",
  "amount": 13
}

###
// Incorrect amount (Некоректная сумма)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": "12345678910111213147",
  "amount": -12
}

###
// Incorrect amount (Некоректная сумма)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": "12345678910111213147",
  "amount": 0
}


###     TRANSFERS BETWEEN CLIENTS(ПЕРЕВОДЫ МЕЖДУ КЛИЕНТАМИ)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

// Making a transfer of the client with id = 4f9a97c4-8300-11ee-b962-0242ac120010 from the account: 12345678910111213150
// to the account: 12345678910111213148 (transfer from RUR to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010 со счета: 12345678910111213150
// на счет: 12345678910111213148 (перевод с RUR на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 5.00
}

###
// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

// Accept transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###
#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120010 from account: 12345678910111213149
// to account: 12345678910111213147 (transfer from USD to USD)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010 со счета: 12345678910111213149
// на счет: 12345678910111213147 (перевод с USD на USD)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213149,
  "accountNumberRecipient": 12345678910111213147,
  "amount": 1.01
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Accept transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213149

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
#----------------------------------------------------------------#

// (Добавление средств на счет отправителя)
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213150,
  "amount": 100000
}

###

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120010 from account: 12345678910111213150
// to account: 12345678910111213147 (transfer from RUR to USD)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120010 со счета: 12345678910111213150
// на счет: 12345678910111213147 (перевод с RUR на USD)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213147,
  "amount": 200
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###

// Accept transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 3.24
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Accept transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 1
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Reject transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "rejected"
}

###

// Check after reject (Проверка после отклонения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 60
}

###

// Making another transfer by the same client from the same account
// Making a transfer of a client with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение еще одного перевода тем же клиентом с того же счета
// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 60
}

###
// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Accept second transfer (Подтверждение второго перевода)
// Accept transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Reject first transfer (Отклонение первого перевода)
// Reject transfer (Подтверждение перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "rejected"
}

###
// Check after reject (Проверка после отклонения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Client not found (Клиент не найден)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120099/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 50
}

###
// Incorrect account number (Некорректный номер карты)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 50
}

###
// Account not found (Счет не найден)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213151,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 50
}

###
// Invalid transfer, account number = 12345678910111213151 not found
// (Невалидная транзакция, счет получателя с номером 12345678910111213151 не найден)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213151,
  "amount": 50
}

###

#----------------------------------------------------------------#

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

// Invalid transaction (the sender's amount must be less than his balance)
// Невалидная транзакция (сумма которую отправляет клиент должна быть меньше его баланса)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 500000
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

#----------------------------------------------------------------#
// Tranfer from blocked account (Перевод с заблокированного счета)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213146,
  "accountNumberRecipient": 12345678910111213148,
  "amount": 1
}

###
// Tranfer to blocked account (Перевод на заблокированный счет)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120010/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213150,
  "accountNumberRecipient": 12345678910111213146,
  "amount": 50
}

###
// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120011/accounts/12345678910111213148

###

#----------------------------------------------------------------#
// Transaction not found (Транзакция не найдена)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/4f9a97c4-8300-11ee-b962-0242ac120099
Content-Type: application/json

{
  "status": "accepted"
}

###

// Transaction status not found (Не правильное состояние транзакции)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/2c327804-2a88-4c20-bcf9-18d785a7fc79
Content-Type: application/json

{
  "status": "ACCEPT"
}

###

// Invalid transaction status lenght (Невалидная длина статуса транзакции)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/2c327804-2a88-4c20-bcf9-18d785a7fc79
Content-Type: application/json

{
  "status": "Aс"
}

###
#----------------------------------------------------------------#

// Making a transaction during which another one occurs and
// the client's balance becomes less than the transferred amount

// Совершение транзакции во время которой происходит еще одна транзакция
// и баланс клиента становится меньше переводимой суммы

// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 1
}

###
// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 40
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Second transfer accept (Подтверждение второго перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// First transfer accept (Подтверждение первого перевода)
// Amount must be less account balance (Сумма перевода должна быть меньше текущего баланса)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###
#----------------------------------------------------------------#

// Making a transaction during which another transaction occurs
// and the balance of one of the accounts is blocked

// Совершение транзакции во время которой происходит еще одна транзакция
// и один из счетов блокируют

// Adding an amount to an account: 12345678910111213148 client with id = 4f9a97c4-8300-11ee-b962-0242ac120011
// Зачисление средств на счет: 12345678910111213148, клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011
PATCH http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts
Content-Type: application/json

{
  "accountNumber": 12345678910111213147,
  "amount": 1000
}

###
// Check before transfer (Проверка до перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###

// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 1
}

###
// Making a client transfer with id = 4f9a97c4-8300-11ee-b962-0242ac120012 from account: 12345678910111213147
// to account: 12345678910111213150 (transfer from USD to RUR)

// Совершение перевода кслиента с id = 4f9a97c4-8300-11ee-b962-0242ac120012 со счета: 12345678910111213147
// на счет: 12345678910111213150 (перевод с USD на RUR)
POST http://localhost:8081/api/v1/clients/4f9a97c4-8300-11ee-b962-0242ac120012/transfer
Content-Type: application/json

{
  "accountNumberSender": 12345678910111213147,
  "accountNumberRecipient": 12345678910111213150,
  "amount": 1
}

###

// Second transfer accept (Подтверждение второго перевода)
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###

// Check after transfer (Проверка после перевода)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150

###                      Need to change isBlocked status

// First transfer accept (Подтверждение первого перевода)
// Account is blocked, you can't do transfer
PATCH http://localhost:8081/api/v1/staff/transactions/expectation/{transactionId}
Content-Type: application/json

{
  "status": "accepted"
}

###                      Don't forget to change isBlocked status
// Check after accept (Проверка после подтверждения)
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120012/accounts/12345678910111213147

###
GET http://localhost:8081/api/v1/4f9a97c4-8300-11ee-b962-0242ac120010/accounts/12345678910111213150


###                CREATE NEW CLIEN(СОЗДАНИЕ НОВОГО КЛИЕНТА)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Create new client (Создание нового клиента)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Maxim",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###

// Create new client (Создание нового клиента)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1111 222222",
    "firstName": "Lubov",
    "lastName": "Lubova",
    "age": 34,
    "email": "lubovLubova@gmail.com",
    "gender": "WOMAN",
    "address": "Саратов, улица Пушкина, д. 5, к. 1, кв 56",
    "phone": "+7 (909) 5550125"
  }
}

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Invalid personal ID (Невалидный personal ID)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2",
    "firstName": "Maxim",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###

// Invalid personal ID (Невалидный personal ID)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 2222222222222222222222222222222222222222",
    "firstName": "Maxim",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###

// Invalid personal ID (Невалидный personal ID)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": null,
    "firstName": "Maxim",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###

// Invalid Firstname (Невалидное имя)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid Firstname (Невалидное имя)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": null,
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid Firstname (Невалидное имя)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid age (Невалидный возраст)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": -13,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###

###
// Invalid age (Невалидный возраст)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 151,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid age (Невалидный возраст)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 2147483648,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid age (Невалидный возраст)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": null,
    "email": "maximMaximov@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid email (Невалидная почта)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "qwerty",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid email (Невалидная почта)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid gender (Невалидный пол)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MANNNN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid address (Невалидный адрес)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Mo",
    "phone": "+7 (909) 5550125"
  }
}

###
###
// Invalid address (Невалидный адрес)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "lwemclkwemkclmwelkmeklvlkvkldmvkmwekvwoevoienvonwvovewfwefwefwefwefhiwrejfirejgojreigjerigjoerijgioeiermvirmeovieroivneorvionwroivnwienviwenvoiewnvoinweoivnweiovnoiwnviowenvoiwenvioebwvionweiovnwevnewio",
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid address (Невалидный адрес)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": null,
    "phone": "+7 (909) 5550125"
  }
}

###
// Invalid phone (Невалидный номер телефона)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": ""
  }
}

###
// Invalid phone (Невалидный номер телефона)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": null
  }
}

###
// Invalid phone (Невалидный номер телефона)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+7 (909) 55501251"
  }
}

###
// Invalid phone (Невалидный номер телефона)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "+790955501251"
  }
}

###
// Invalid phone (Невалидный номер телефона)
POST http://localhost:8081/api/v1/staff/clients
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "2222 222222",
    "firstName": "Max",
    "lastName": "Maximov",
    "age": 34,
    "email": "email@gmail.com",
    "gender": "MAN",
    "address": "Moscow, Khimkinsky bulvar, 334, 26",
    "phone": "7 909 55501251"
  }
}


###          GETTING CLIENT INFORMATION(ПОЛУЧЕНИЕ ИНФОРМАЦИИ О КЛИЕНТЕ)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Getting client information(Получение информации о клиенте)
GET http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120010

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Client not found(Клиент не найден)
GET http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120099


###        UPDATING CLIENT INFORMATION (ОБНОВЛЕНИЕ ИНФОРМАЦИИ О КЛИЕНТЕ)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Update client information with id = 4f9a97c4-8300-11ee-b962-0242ac120010
// (Обновление информации о пользователе с id = 4f9a97c4-8300-11ee-b962-0242ac120010)
PUT http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120010
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1234 QW45678",
    "firstName": "Luffy",
    "lastName": "Monkey'D",
    "age": 18,
    "email": "luffy@marinford.com",
    "gender": "MAN",
    "address": "East Blue",
    "phone": "+111 (123) 555-1234"
  }
}

###
// Getting update client information(Получение обновленной информации о клиенте)
GET http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120010

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Client not found(Клиент не найден)
PUT http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120099
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1234 QW45678",
    "firstName": "Luffy",
    "lastName": "Monkey'D",
    "age": 18,
    "email": "luffy@marinford.com",
    "gender": "MAN",
    "address": "East Blue",
    "phone": "+111 (123) 555-1234"
  }
}

###

// Infalid age (Невалидный возраст)
PUT http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120010
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1232 QW45678",
    "firstName": "Luffy",
    "lastName": "Monkey'D",
    "age": -1,
    "email": "luffy@marinford.com",
    "gender": "MAN",
    "address": "East Blue",
    "phone": "+111 (123) 555-1234"
  }
}

###
// Update personal ID (Обновляем personal ID)
PUT http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120010
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1232 QW45699",
    "firstName": "Luffy",
    "lastName": "Monkey'D",
    "age": 10,
    "email": "luffy@marinford.com",
    "gender": "MAN",
    "address": "East Blue",
    "phone": "+111 (123) 555-1234"
  }
}

###
// Infalid update with same personal Id (Невалидный обновление, клиент с таким personal ID уже существует)
PUT http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120011
Content-Type: application/json

{
  "clientInfo": {
    "personalID": "1232 QW45699",
    "firstName": "Luffy",
    "lastName": "Monkey'D",
    "age": 14,
    "email": "luffy@marinford.com",
    "gender": "MAN",
    "address": "East Blue",
    "phone": "+111 (123) 555-1234"
  }
}


###                CREATE NEW ACCOUNT (СОЗДАНИЕ НОВОГО СЧЁТА)

#----------------------------------------------------------------------------#
#                POSITIVE TEST CASES (ВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)            #
#----------------------------------------------------------------------------#

// Creating a new account with a client with id = 4f9a97c4-8300-11ee-b962-0242ac120011, the account currency is RUR
// (Создание нового счета у клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011, валюта счета это - RUR)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120011
Content-Type: application/json

{
  "currency": "RUR"
}

###

// Creating a new account with a client with id = 4f9a97c4-8300-11ee-b962-0242ac120011, the account currency is USD
// (Создание нового счета у клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011, валюта счета это - USD)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120011
Content-Type: application/json

{
  "currency": "USD"
}

###

// Creating a new account with a client with id = 4f9a97c4-8300-11ee-b962-0242ac120011, the account currency is USD
// (Создание нового счета у клиента с id = 4f9a97c4-8300-11ee-b962-0242ac120011, валюта счета это - USD)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120011
Content-Type: application/json

{
  "currency": "usd"
}

###

#----------------------------------------------------------------------------#
#                NEGATIVE TEST CASES (НЕВЕРНЫЕ РЕЗУЛЬТАТЫ ЗАПРОСОВ)          #
#----------------------------------------------------------------------------#

// Client not found(Клиент не найден)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120099
Content-Type: application/json

{
  "currency": "USD"
}

###

// Currency not found(Валюта не найден)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120099
Content-Type: application/json

{
  "currency": "USDT"
}

###

// Currency must not be blank(Значение не должно быть пустым)
POST http://localhost:8081/api/v1/staff/clients/4f9a97c4-8300-11ee-b962-0242ac120099
Content-Type: application/json

{
  "currency": ""
}

###